# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160316_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreeoffitness',
            name='person',
        ),
        migrations.RemoveField(
            model_name='department',
            name='person',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='person',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='person',
        ),
        migrations.RemoveField(
            model_name='group',
            name='department',
        ),
        migrations.RemoveField(
            model_name='okso',
            name='person',
        ),
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
        migrations.AddField(
            model_name='person',
            name='OKSO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.OKSO'),
        ),
        migrations.AddField(
            model_name='person',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DegreeOfFitness'),
        ),
        migrations.AddField(
            model_name='person',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Faculty'),
        ),
        migrations.AddField(
            model_name='person',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Grade'),
        ),
    ]
