# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OKSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OKSO', models.CharField(max_length=255, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'\xd0\x98\xd0\xbc\xd1\x8f', max_length=100)),
                ('middle_name', models.CharField(default=b'\xd0\x9e\xd1\x82\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe', max_length=100)),
                ('last_name', models.CharField(default=b'\xd0\xa4\xd0\xb0\xd0\xbc\xd0\xb8\xd0\xbb\xd0\xb8\xd1\x8f', max_length=100)),
                ('personal_record', models.CharField(default=b'\xd0\x9b\xd0\xb8\xd1\x87\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xb4\xd0\xb5\xd0\xbb\xd0\xbe', max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('birth_place', models.CharField(default=b' ', max_length=100)),
                ('document_serial_number', models.CharField(default=b' ', max_length=100)),
                ('document_number', models.CharField(default=b' ', max_length=100)),
                ('issued_by', models.CharField(default=b' ', max_length=100)),
                ('birthplace', models.CharField(default=b'\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0', max_length=100)),
                ('address', models.CharField(default=b'\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='okso',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
