# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160316_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militarycommissariat',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='military',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MilitaryCommissariat'),
        ),
    ]
